author:
  name: Chiemi Ma
  url: thegrid.ai/chiemi
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 1
  brandStrength: 0.1601035
  lightness: 1
  brandColors:
    - '#151419'
    - '#313139'
    - '#620E11'
    - '#FF2727'
    - '#744856'
  rhythmicContrast: 1
typography_spectrum: 0.947018
navigation: []
layout_spectrum: 1
name: Chiemi
